# Generated by Django 5.2.4 on 2025-07-17 10:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutuspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='body',
            field=wagtail.fields.StreamField([('hero_section', 3), ('text_image_section', 6), ('value_section', 11), ('milestone_section', 14), ('team_section', 17), ('logo_section', 21), ('rich_text', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('background_image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'left', 'help_text': 'left or right'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 4), ('image', 2), ('image_position', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use a CSS class or name'}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 0), ('description', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('year', 0), ('title', 0), ('description', 8)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('milestones', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 0), ('bio', 8), ('photo', 2)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('heading', 0), ('members', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('heading', 0), ('logos', 20)]], {})}),
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
