# Generated by Django 5.2.4 on 2025-07-17 11:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aboutuspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='body',
            field=wagtail.fields.StreamField([('hero_section', 3), ('text_image_section', 6), ('value_section', 11), ('milestone_section', 15), ('team_section', 18), ('logo_section', 22), ('rich_text', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('background_image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'left', 'help_text': 'left or right'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 4), ('image', 2), ('image_position', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an icon image', 'required': False}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 0), ('description', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image shown on left', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('year', 0), ('title', 0), ('description', 8)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('image', 12), ('milestones', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 0), ('bio', 8), ('photo', 2)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 0), ('members', 17)]], {}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('heading', 0), ('logos', 21)]], {})}),
        ),
    ]
